# For example with nox, see:
# https://github.com/theacodes/nox/blob/master/.travis.yml

# branches:
#   only:
#     master

os:
  - linux  # TODO: test on other OSs?

language: python

# python:
#   - '2.7'
#   - '3.5'
#   - '3.6'
#   # - '3.7'  # Explicitly included below for docs building
#   # - "3.7-dev"  # 3.7 development branch
#   # - "3.8-dev"  # 3.8 development branch
#   # - "nightly"  # nightly build

matrix:
  include:
    - python: '3.5'
      env: NOXSESSIONS="tests-3.5"
    - python: '3.6'
      env: NOXSESSIONS="tests-3.6"
    - python: '3.7'  # Also test docs with latest supported python version
      dist: xenial  # required for Python >= 3.7
      env: NOXSESSIONS="coverage-3.7 lint docs"
    - python: '3.6'
      env: NOXSESSIONS="tests-2.7"
  allow_failures:
    - python: '3.6'
      env: NOXSESSIONS="tests-2.7"
    - python: '3.5'
      env: NOXSESSIONS="tests-3.5"

cache: pip

install:
  - pip install pipenv nox
  # - pipenv --bare install --deploy --dev

script:
  - nox --non-interactive -s $NOXSESSIONS

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: schuderer
  password:
    secure: RG3A8u/F5Dff6O7E5y/BxwevEPwyI8sp9JasvfWDjUfRHQAM1xNJMqaYe5D+tDuD6yVIIJQVjmtHz6pu8O+KF8W4PZ/Qbxx5Fhupwmw7ugAcQBcieXLZdzkMQvCDsVNQyZL0+/z5uq4zU0X1pXS9Dv3sXCNzRn/Cfsh/K3KTbaNBc/1zu4Y+oRrkYCk7O+X8R77xLsBP+RX5BYxk0H9rtzNfiw0rwSUlZ7IB4wzwWNFHO8LYvu6t4W4ML6PROroU70C0u4rhExBVxvWmDypM/TAwfBmQ5GgUOuIrCOEDZlID18uvQzYpwmnfBT+HI95uh+jUnQflEbwbtsXxylIOUw/tRPyu8aRhmuAsMdX6wfEaCgo8udNp3n3YzXiDYQUX1//3xoiWRkp3nh4pJEzmD91csBo/Go/hUWUETZfyfVamKsUMMcrQ+PyNhgXgTrWy8K/OSjrGxnNW6jLSU4ofqOv2UWB+e3G5Me0Wm/WlCqC3jnr5TDM+aSKKnclb8FB7o8Nim7ByEMLIWf0Nsraqi5unkUTSHwfU1745h0uCdo0afofmJEsjytTjcc2is4fbub+JcUwIHkwr1/57YXFBuy918rwLDUR9dNcnwsZF0VmLmnkknKWyzkQKJQU9NwJArEYW52c2Vv5oyrfOUVR+QZmhyxfpeq2ksaMs/t3gaXU=
  on:
    tags: true
    repo: schuderer/mllaunchpad
    python: 3.7
    condition: "$NOXSESSION = \"coverage-3.7 lint docs\""


# deploy:
#   provider: pypi
#   user: theacodes
#   password:
#     secure: ETRTnYg+8cilT0/HidhyPljERgE/u0boKdH9TW+JrY0De40Km5C+TUmPagKJuwPx1Gw8HNN1vN7M1pqaQ/flQaY9iNbuJZr5ZaApiZW1pw5/nO2wWoANx0hiChdjvwbJZdqUFEoba6MS9aBY7TroFlLjW6dUg8MZFSiUFRQDF9rTCyzB/juC7wiLTgrjlFpOvaOmf1qpVOajY5kfn8MLELms8itRUa04X4kqqgtOfifoA1CevObrScGSXlpPtqmoxUrCmwbnHu9qnqgAWLHe3y7fI4ZqscYQv/JCW8NdJgqMTn0jctLXibHt5vC/DtUYo47mFSRBfn55ZwAFiV6IiwVbtDKby0ZdNO2uIFn4B/7l0qrLTwnZbRy4vkPqEeJoS75vl4JQrauGmI+hgdtesHjZxLzs94H4vINVt0fGpkYqbgtMQO8HUQnnj0FJXcGKo4A5OuLjnk5+rgTSvLT/5qNg/cyve5BXkn1ib6ecah21MHSQyhl5CxIFBH6S6BRrGoxXluLqXPVv/w+QA0lxXCpAPfbHuMt4r9522YN/XfGQNHfNqK/836UbLEX5ZXZiZLl01IvVPl+3eC/Qmpc+tNXb51d53Qsm89VtaNGGvuV2eLPBR+gfXcQ8wFB1HW3Q3oshHCGW4KKApyzyYKWq27JPlGV13Yh+NMHWs9PGHyI=
#   on:
#     tags: true
#     distributions: sdist bdist_wheel
#     repo: theacodes/nox
#     condition: "$NOXSESSION = \"tests-3.6\""

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
